#!/usr/bin/env zsh

# global settings
# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12 
yabai -m config right_padding                12
yabai -m config window_gap                   12

# Rules
yabai -m rule --add app="^Calendar$"           manage=off
yabai -m rule --add app="^Dictionary$"         manage=off
yabai -m rule --add app="^Disk Utility$"       manage=off
yabai -m rule --add app="^Simulator$"          manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^システム環境設定$"   manage=off
yabai -m rule --add app=".*AnyConnect.*"       manage=off

# restore position of floating windows when they are manually unfloated
# ~/dotfiles/yabai/yabai_restore.sh

echo "yabai configuration loaded.."

# killall limelight &> /dev/null
# limelight -c ~/.limelightrc &> /dev/null &
